### ISSUE TITLE
Hi John Doering

### ISSUE THREAD

**Issue by leonmelson** [ghostlander/NeoScrypt#4]
Hi

I love Neoscrypt and Phoenixcoin and appreciate the hard work and time that you guys have put into this.

I am trying to get Phoenixcoin and Neoscrypt to work on Unomp but I am having a hardtime I have done allot of research but only got some info.

This is what I have found.
http://phoenixcoin.org/archive/neoscrypt_v1.pdf

Scrypt is normaly : (1024, 1, 1) N = 1024, r = 1, p = 1
AND
Neoscrypt = (128, 2, 1)

So in unomp I change the phoenixcoin.json to
{
    "name"       : "Phoenixcoin",
    "symbol"     : "PXC",
    "algorithm"  : "neoscrypt",
    "nValue"  : "128",
     "rValue"  : "2"
}
I am thinking leaving p is ok because the default will be 1.
But this still does not work

The pool works fine but when the pool discovers a block it fails.

Any help will be appreciated.

My goal is to get neoscrypt working on Unomp and then helping others to add it to there pools so neoscrypt and phoenixcoin demand can go up and in turn its value raising.

Thx
Leon Melson

**Comment by ghostlander** [comment]
Hello Leon,

Phoenixcoin uses SHA-256d for block hashing and NeoScrypt for proof-of-work hashing. The first part is easy while the second requires additional code. For example, P2Pool loads a NeoScrypt module which is basically the reference C code wrapped up.

https://github.com/ghostlander/p2pool-neoscrypt

I recall the first NeoScrypt NOMP pool has got the following commits.

https://github.com/Griffitsj/node-stratum-pool/commit/9a7a1388f80e3c3e771b85e798455aa580bec65b
https://github.com/Griffitsj/node-stratum-pool/commit/be294c538bb6d8ec562d70b49ddd2e13e9353d10

**Comment by leonmelson** [comment]
Hi

Thx for the data.

I will look into it and test again.

Thx
Leon

**Comment by leonmelson** [comment]
Hi

It seems I got it working in the newer version of unomp this sections was
not the lib/jobManager.js
Griffitsj/node-stratum-pool@
<https://github.com/Griffitsj/node-stratum-pool/commit/be294c538bb6d8ec562d70b49ddd2e13e9353d10>
be294c5
<https://github.com/Griffitsj/node-stratum-pool/commit/be294c538bb6d8ec562d70b49ddd2e13e9353d10>
<https://github.com/Griffitsj/node-stratum-pool/commit/be294c538bb6d8ec562d70b49ddd2e13e9353d10>

So I added it and now it woks

Thx your so much for your help

Leon Melson
